config/routes.rb
Sorcery::Application.routes.draw do
  

 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 resources :users 
 resources :sessions
 resources :buyers
 
 root :to => "users#index"

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  attr_accessible :apellidos, :direccion, :fch_ncto, :nombres

  validates :nombres, :presence => true,
  :length => { :maximum => 30 }
  
   validates :apellidos, :presence => true,
  :length => { :maximum => 30 }

  validates_presence_of :direccion 

  validates_presence_of :fch_ncto
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :username, :email, :password, :password_confirmation
 
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_authenticated
 	redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

  before_filter :require_login

  
  def index
    @buyers = Buyer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buyers }
    end
  end

  
  def show
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buyer }
    end
  end

  
  def new
    @buyer = Buyer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buyer }
    end
  end

  
  def edit
    @buyer = Buyer.find(params[:id])
  end


  def create
    @buyer = Buyer.new(params[:buyer])

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render json: @buyer, status: :created, location: @buyer }
      else
        format.html { render action: "new" }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      if @buyer.update_attributes(params[:buyer])
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @buyer = Buyer.find(params[:id])
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
  	user = login(params[:username], params[:password], params[:remember_me])
    if user
       redirect_back_or_to buyers_path
    else
        flash.now.alert = "Email or password was invalid"
        render :new
    end
  end

  def destroy
  	logout
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url,:notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buyers/_form.html.erb
<%= simple_form_for(@buyer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombres %>
    <%= f.input :apellidos %>
    <%= f.input :direccion %>
    <%= f.input :fch_ncto %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<h1>Listing buyers</h1>

<table>
  <tr>
    <th>Nombres</th>
    <th>Apellidos</th>
    <th>Direccion</th>
    <th>Fch ncto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buyers.each do |buyer| %>
  <tr>
    <td><%= buyer.nombres %></td>
    <td><%= buyer.apellidos %></td>
    <td><%= buyer.direccion %></td>
    <td><%= buyer.fch_ncto %></td>
    <td><%= link_to 'Show', buyer %></td>
    <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
    <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<h1>New buyer</h1>

<%= render 'form' %>

<%= link_to 'Back', buyers_path %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombres:</b>
  <%= @buyer.nombres %>
</p>

<p>
  <b>Apellidos:</b>
  <%= @buyer.apellidos %>
</p>

<p>
  <b>Direccion:</b>
  <%= @buyer.direccion %>
</p>

<p>
  <b>Fch ncto:</b>
  <%= @buyer.fch_ncto %>
</p>


<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Auth Example</title>
	  <%= stylesheet_link_tag    "application" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  	<div id="container">
		  	<div class="user_nav">
		      <% if current_user %>
		        Logged in as <%= current_user.email %>.
		        <%= link_to "Log out", logout_path %>
		      <% else %>
		        <%= link_to "Sign up", signup_path %> or
		        <%= link_to "log in", login_path %>.
		      <% end %>
		    </div>
		    <% flash.each do |name, msg| %>
		      <%= content_tag :div, msg, :id => "flash_#{name}" %>
		    <% end %>
		    <%= yield %>
	    </div>
	</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>usuario </h1> 
<p><%= link_to "buyers", buyers_path %></p>

<!--<h1>Users#index</h1>-->
<!--<p>Find me in app/views/users/index.html.erb</p>-->

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>